- name: Setup Node.js
  uses: actions/setup-node@v3
  with:
    node-version: "14"

- name: Calculate and Update Experience
  run: |
    const fs = require('fs');

    const startDate = new Date('2022-08-01');  // Replace with your actual start date
    const currentDate = new Date();

    let totalMonths = (currentDate.getFullYear() - startDate.getFullYear()) * 12;
    totalMonths += currentDate.getMonth() - startDate.getMonth();

    if (currentDate.getDate() < startDate.getDate()) {
      totalMonths--;
    }

    const years = Math.floor(totalMonths / 12);
    const months = totalMonths % 12;

    const experienceText = `${years} years and ${months} months`;

    let readmeContent = fs.readFileSync('README.md', 'utf8');
    readmeContent = readmeContent.replace(/<!-- EXPERIENCE_PLACEHOLDER -->/g, experienceText);

    fs.writeFileSync('README.md', readmeContent);
