name: Update README with Experience Duration

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Setup Git
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Create update-experience.js script
        run: |
          cat << 'EOF' > update-experience.js
          const fs = require('fs');

          // Start date of your experience
          const startDate = new Date('2023-09-01');
          const currentDate = new Date();

          // Calculate the total months of experience
          let totalMonths = (currentDate.getFullYear() - startDate.getFullYear()) * 12;
          totalMonths += currentDate.getMonth() - startDate.getMonth();

          // Adjust if the current day of the month is before the start day
          if (currentDate.getDate() < startDate.getDate()) {
            totalMonths--;
          }

          // Calculate years and remaining months
          const years = Math.floor(totalMonths / 12);
          const months = totalMonths % 12;

          // Format the experience text
          const experienceText = `${years} years and ${months} months`;

          // Read the README.md file
          let readmeContent = fs.readFileSync('README.md', 'utf8');

          // Replace the existing experience placeholder with the new calculated experience
          const newContent = readmeContent.replace(
            /- ⚡ \*\*Experience:\*\*.*$/m,
            `- ⚡ **Experience:** ${experienceText}`
          );

          // Write the updated content back to README.md
          fs.writeFileSync('README.md', newContent);
          EOF

      - name: Run update-experience.js
        run: node update-experience.js

      - name: Commit and Push Changes
        run: |
          git add README.md
          git commit -m "Update experience duration in README [skip ci]" || exit 0
          git push origin HEAD:${{ github.ref }}
